### PR TITLE
Feature/extensions

### PR DESCRIPTION
**Pull request by jbrumwell**
Had to catch-up my didn't realize my fork was behind until after, here is what I'm currently working with. Let me know your thoughts
- Switch to babel
- Switch to eslint
- Upgrade dependencies
- Switch to knex for additional support
- Implement `dialects` for sql and js
- Implement `init` command with backwards compatiblity
- add some readme information
#8

### CODE REVIEW

**Comment by jbrumwell** [comment]
There are conflicts, once we are okay with the design I'll fix those up :)

**Comment by jbrumwell** [comment]
Merged master and fixed a bug in `create` command

**Comment by jbrumwell** [comment]
@bjyoungblood any feedback? I'm not going to worry about an cypher extension as we need to pull data from sql at the same time but if your good would be nice to get this published :) I've been using it locally without issue for `js` and `sql` files but not sure if I effected your on publish.

**Comment by bjyoungblood** [comment]
@jbrumwell sorry, I was out of town for a bit and forgot about this.

The only thing I noticed is that babel (and related) should be devDependencies. The prepublish script takes care of rebuilding `dist/` prior to running `npm publish`.

**Comment by jbrumwell** [comment]
@bjyoungblood no worries at all :) I hope you were out of town on pleasure and not business :+1: I've moved the dependencies for babel to dev-dependencies :)

**Comment by bjyoungblood** [comment]
Looks great! This will really come in handy shortly, as I have a legacy MySQL database to work with. ;)

**Comment by bjyoungblood** [comment]
Published `v1.0.0`.

**Pull request merged**
